### ISSUE TITLE
Putting a border around notification

### ISSUE THREAD

**Issue by kriiv** [marcelodolza/iziToast#165]
Is there a way to put a border around the notification? It seems I can't just add a border styling...

**Comment by Hissvard** [comment]
Hello,

Mind sharing an example of your desired styling?

Like you said, simply using

```css
.iziToast {
    border: 3px solid black;
}
```
wouldn't work because of specifity issues.
So either use !important or override the styled versions one by one.
